Metrics exporter cache requests that fail with an unrecoverable error
GoogleCloudPlatform/opentelemetry-operations-go pull request #768
Opened 2023-11-09 16:55 UTC by avilevy18

Fixes [#765](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/765)

When the metrics exporter fails to create a new metric descriptor any non-recoverable grpc errors will update the cache, preventing further CMD calls.

2023-11-09 19:18 UTC, punya commented
/gcbrun

2023-11-09 19:34 UTC, punya requested changes
Please add some test coverage

2023-11-13 17:33 UTC, dashpole commented
@avilevy18 I'm planning to cut a release later today.  If you can add test coverage by then, then we can include it.  Let me know if we can help direct you.

2023-11-13 20:32 UTC, dashpole commented
/gcbrun

2023-11-13 20:37 UTC, dashpole commented
you can run `make fieldalignment` to fix the error

2023-11-13 21:36 UTC, dashpole commented
/gcbrun

2023-11-13 21:38 UTC, dashpole commented on exporter/collector/metrics.go
> +type monitoringClient interface {
```suggestion
// monitoringClient is the subset of monitoring.MetricClient this exporter uses,
// and allows us to mock the implementation for testing.
type monitoringClient interface {
```

2023-11-13 21:38 UTC, dashpole commented on exporter/collector/metrics.go
> +func isNotRecoverable(err error) bool {
```suggestion
// isNotRecoverable returns true if the error is permanent.
func isNotRecoverable(err error) bool {
```

2023-11-13 21:38 UTC, dashpole commented
/gcbrun

2023-11-13 21:58 UTC, dashpole approved these changes

2023-11-13 22:00 UTC, merged